version: "2"
volumes:
  database-data:
services:
  docker-ecosystem-client:
    image: ${IMAGE_REGISTRY}/docker-ecosystem-client:${IMAGE_VERSION}
    build: .
    ports:
      - '80'
    links:
      - java-service
      - node-service
  java-service:
    image: ${IMAGE_REGISTRY}/docker-ecosystem-java-service
    links:
      - database
    depends_on:
      - migration
  node-service:
    image: ${IMAGE_REGISTRY}/docker-ecosystem-node-service
    links:
      - database
    depends_on:
      - migration
  migration:
    image: ${IMAGE_REGISTRY}/docker-ecosystem-migration
    links:
      - database
  database:
    image: postgres:9.5.1
    volumes:
      - database-data:/var/lib/postgres/data
